version: '3.3'
services:

  ethernode:
   build: ./ethernode
   environment:
     LOG_LEVEL: 2 #0=silent, 1=error, 2=warn, 3=info, 4=core, 5=debug, 6=detail
     DELETE_OLD_BLOCKCHAIN: 0
     MINING: 0
   ports:
     - 30303:30303
     - 30303:30303/udp
   volumes:
     - ./ethernode/devnet:/root/devnet
     - ./ethernode/rinkeby:/root/rinkeby
     - ./data/ethernode/.ethereum:/root/.ethereum
     - ./data/ethernode/.ethash:/root/.ethash
     - ./data/ethernode/geth_ipc:/root/geth_ipc
   entrypoint: echo -e "need use bash to start";
   logging:
     options:
       max-size: 1000m
   restart: "no"